<a href="https://colab.research.google.com/github/renupareek27/my-projects/blob/main/DA_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [ ]:
# create a list 'data'
data = [[1,'Neha','Mgr'],[2,'Nisha','Programmer'],[3,'Saloni','Clerk'],[4,'Amit','Tester']]

In [ ]:
# Create dataframe from List
df1 = pd.DataFrame(data)

In [ ]:
df1

   0       1           2
0  1    Neha         Mgr
1  2   Nisha  Programmer
2  3  Saloni       Clerk
3  4    Amit      Tester

In [ ]:
# Add column names
df2 = pd.DataFrame(data,columns=['Eid','Ename','Job'])

In [ ]:
df2

   Eid   Ename         Job
0    1    Neha         Mgr
1    2   Nisha  Programmer
2    3  Saloni       Clerk
3    4    Amit      Tester

In [ ]:
# Add row names
df3 = pd.DataFrame(data,columns=['Eid','Ename','Job'],index=['E1','E2','E3','E4'])

In [ ]:
df3

    Eid   Ename         Job
E1    1    Neha         Mgr
E2    2   Nisha  Programmer
E3    3  Saloni       Clerk
E4    4    Amit      Tester

In [ ]:
# Create a Dictionary 'data'
data = {
    'Eid':[100,200,300],
    'Ename':['Disha','Manali','Reva'],
    'Job':['Mgr','Programmer','HR']
}

In [ ]:
# Create dataframe from Dictionary
df4 = pd.DataFrame(data)

In [ ]:
df4

   Eid   Ename         Job
0  100   Disha         Mgr
1  200  Manali  Programmer
2  300    Reva          HR

In [ ]:
# We can add row names also

df4 = pd.DataFrame(data,index=('E1','E2','E3'))

In [ ]:
df4

    Eid   Ename         Job
E1  100   Disha         Mgr
E2  200  Manali  Programmer
E3  300    Reva          HR

In [ ]:
# Read from csv files
import pandas as pd
univ = pd.read_csv("/content/Universities.csv")

In [ ]:
univ

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [ ]:
type(univ)

pandas.core.frame.DataFrame

In [ ]:
univ.head()

       Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0     Brown  1310     89      22       13     22704        94
1   CalTech  1415    100      25        6     63575        81
2       CMU  1260     62      59        9     25026        72
3  Columbia  1310     76      24       12     31510        88
4   Cornell  1280     83      33       13     21864        90

In [ ]:
univ.head(13)

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94

In [ ]:
univ.tail()

          Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
20   UMichigan  1180     65      68       16     15470        85
21       UPenn  1285     80      36       11     27553        90
22         UVA  1225     77      44       14     13349        92
23  UWisconsin  1085     40      69       15     11857        71
24        Yale  1375     95      19       11     43514        96

In [ ]:
univ.tail(2)

          Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
23  UWisconsin  1085     40      69       15     11857        71
24        Yale  1375     95      19       11     43514        96

In [ ]:
univ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Univ      25 non-null     object
 1   SAT       25 non-null     int64
 2   Top10     25 non-null     int64
 3   Accept    25 non-null     int64
 4   SFRatio   25 non-null     int64
 5   Expenses  25 non-null     int64
 6   GradRate  25 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.5+ KB

In [ ]:
univ.describe()

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

In [ ]:
# Indexes are used to access rows. Default indexing starts from 0.
# We can make a column as an index to uniquely identify a record
univ.head(3)

      Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0    Brown  1310     89      22       13     22704        94
1  CalTech  1415    100      25        6     63575        81
2      CMU  1260     62      59        9     25026        72

In [ ]:
univ.columns

Index(['Univ', 'SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate'], dtype='object')

In [ ]:
udf = pd.read_csv('Universities.csv',index_col='Univ') # or index_col=0, to make Univ column to act as an index,

In [ ]:
udf.head(3) # check index of dataframe

          SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown    1310     89      22       13     22704        94
CalTech  1415    100      25        6     63575        81
CMU      1260     62      59        9     25026        72

In [ ]:
udf.columns

Index(['SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate'], dtype='object')

In [ ]:
udf['Expenses']

Univ
Brown           22704
CalTech         63575
CMU             25026
Columbia        31510
Cornell         21864
Dartmouth       32162
Duke            31585
Georgetown      20126
Harvard         39525
JohnsHopkins    58691
MIT             34870
Northwestern    28052
NotreDame       15122
PennState       10185
Princeton       30220
Purdue           9066
Stanford        36450
TexasA&M         8704
UCBerkeley      15140
UChicago        38380
UMichigan       15470
UPenn           27553
UVA             13349
UWisconsin      11857
Yale            43514
Name: Expenses, dtype: int64

In [ ]:
univ['Expenses']

0     22704
1     63575
2     25026
3     31510
4     21864
5     32162
6     31585
7     20126
8     39525
9     58691
10    34870
11    28052
12    15122
13    10185
14    30220
15     9066
16    36450
17     8704
18    15140
19    38380
20    15470
21    27553
22    13349
23    11857
24    43514
Name: Expenses, dtype: int64

In [ ]:
udf.loc['Yale'] # .loc is used to access rows using positional index
# i.e. we got values of a record where row index name is Brown

SAT          1375
Top10          95
Accept         19
SFRatio        11
Expenses    43514
GradRate       96
Name: Yale, dtype: int64

In [ ]:
udf.loc[['MIT','CMU','Duke']]

       SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
MIT   1380     94      30       10     34870        91
CMU   1260     62      59        9     25026        72
Duke  1315     90      30       12     31585        95

In [ ]:
udf.loc['Columbia':'Princeton']

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95

In [ ]:
univ.loc[2:5]

        Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
2        CMU  1260     62      59        9     25026        72
3   Columbia  1310     76      24       12     31510        88
4    Cornell  1280     83      33       13     21864        90
5  Dartmouth  1340     89      23       10     32162        95

In [ ]:
udf[udf['Expenses'] > 45000]

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
CalTech       1415    100      25        6     63575        81
JohnsHopkins  1305     75      44        7     58691        87

In [ ]:
udf[(udf['Expenses'] < 25000) & (udf['GradRate']>75)]

             SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown       1310     89      22       13     22704        94
Cornell     1280     83      33       13     21864        90
Georgetown  1255     74      24       12     20126        92
NotreDame   1255     81      42       13     15122        94
PennState   1081     38      54       18     10185        80
UCBerkeley  1240     95      40       17     15140        78
UMichigan   1180     65      68       16     15470        85
UVA         1225     77      44       14     13349        92

In [ ]:
# Accessing Columns
udf['SAT']

Univ
Brown           1310
CalTech         1415
CMU             1260
Columbia        1310
Cornell         1280
Dartmouth       1340
Duke            1315
Georgetown      1255
Harvard         1400
JohnsHopkins    1305
MIT             1380
Northwestern    1260
NotreDame       1255
PennState       1081
Princeton       1375
Purdue          1005
Stanford        1360
TexasA&M        1075
UCBerkeley      1240
UChicago        1290
UMichigan       1180
UPenn           1285
UVA             1225
UWisconsin      1085
Yale            1375
Name: SAT, dtype: int64

**Access Rows**

In [ ]:
udf.iloc[0] # .iloc is index location which is used to access rows using row index, 0 index record is received

SAT          1310
Top10          89
Accept         22
SFRatio        13
Expenses    22704
GradRate       94
Name: Brown, dtype: int64

**Access columns using positional index**

In [ ]:
udf.iloc[:,2] #all rows and column index 2 i.e. Accept column

Univ
Brown           22
CalTech         25
CMU             59
Columbia        24
Cornell         33
Dartmouth       23
Duke            30
Georgetown      24
Harvard         14
JohnsHopkins    44
MIT             30
Northwestern    39
NotreDame       42
PennState       54
Princeton       14
Purdue          90
Stanford        20
TexasA&M        67
UCBerkeley      40
UChicago        50
UMichigan       68
UPenn           36
UVA             44
UWisconsin      69
Yale            19
Name: Accept, dtype: int64

In [ ]:
udf.iloc[:,2:5] # all rows and columns 2,3,4

              Accept  SFRatio  Expenses
Univ
Brown             22       13     22704
CalTech           25        6     63575
CMU               59        9     25026
Columbia          24       12     31510
Cornell           33       13     21864
Dartmouth         23       10     32162
Duke              30       12     31585
Georgetown        24       12     20126
Harvard           14       11     39525
JohnsHopkins      44        7     58691
MIT               30       10     34870
Northwestern      39       11     28052
NotreDame         42       13     15122
PennState         54       18     10185
Princeton         14        8     30220
Purdue            90       19      9066
Stanford          20       12     36450
TexasA&M          67       25      8704
UCBerkeley        40       17     15140
UChicago          50       13     38380
UMichigan         68       16     15470
UPenn             36       11     27553
UVA               44       14     13349
UWisconsin        69       15     11857
Yale              19       11     43514

**Handling Null Values**

In [ ]:
import pandas as pd
import numpy as np
data = [
    [1,2,3,'M'],
    [np.nan,5,6,np.nan],
    [7,np.nan,8,'F'],
    [np.nan,np.nan,np.nan,'F']
]

In [ ]:
dframe = pd.DataFrame(data,columns=['a','b','c','d'])
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
dframe['a']

0    1.0
1    NaN
2    7.0
3    NaN
Name: a, dtype: float64

In [ ]:
dframe.fillna(0)

     a    b    c  d
0  1.0  2.0  3.0  M
1  0.0  5.0  6.0  0
2  7.0  0.0  8.0  F
3  0.0  0.0  0.0  F

In [ ]:
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
# find avg of column a. It is neglecting null values from that column
avg_a = dframe['a'].mean()
avg_a

np.float64(4.0)

In [ ]:
avg_b = dframe['b'].mean()
avg_b

np.float64(3.5)

In [ ]:
avg_c = round(dframe['c'].mean(),1)
#avg_c = dframe['c'].mean()
avg_c

np.float64(5.7)

In [ ]:
# instead of neglecting null values, fill those values with mean of that column
dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c}) # only numeric column null values are replaced
# original dataframe is not changed yet

     a    b    c    d
0  1.0  2.0  3.0    M
1  4.0  5.0  6.0  NaN
2  7.0  3.5  8.0    F
3  4.0  3.5  5.7    F

In [ ]:
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
dframe.shape[1]

4

In [ ]:
# Change null values of categorical column by finding mode of column
dframe['d'].mode() # we get

0    F
Name: d, dtype: object

In [ ]:
d_mode = dframe['d'].mode()[0]
d_mode
# if bimodal or trimodal data, you will get 2 or 3 values as mode. So you can give [index] of mode to select mode out of 2 or 3

'F'

In [ ]:
dframe.fillna({'d':d_mode})

     a    b    c  d
0  1.0  2.0  3.0  M
1  NaN  5.0  6.0  F
2  7.0  NaN  8.0  F
3  NaN  NaN  NaN  F

In [ ]:
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
# to change original dataframe use inplace=True
dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c,'d':d_mode},inplace=True)

In [ ]:
dframe

     a    b    c  d
0  1.0  2.0  3.0  M
1  4.0  5.0  6.0  F
2  7.0  3.5  8.0  F
3  4.0  3.5  5.7  F

In [ ]:
# To retain your original dataframe and changed dataframe
# Keep original in one dataframe and changed in another dataframe without using inplace=True

# Original Dataframe
dframe = pd.DataFrame(data,columns=['a','b','c','d'])
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
# Assign changed dataframe to new dataframe
newdf = dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c,'d':d_mode})
newdf

     a    b    c  d
0  1.0  2.0  3.0  M
1  4.0  5.0  6.0  F
2  7.0  3.5  8.0  F
3  4.0  3.5  5.7  F

In [ ]:
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
# remove null values
dframe.dropna() # original dataframe is not changed

     a    b    c  d
0  1.0  2.0  3.0  M

In [ ]:
dframe

     a    b    c    d
0  1.0  2.0  3.0    M
1  NaN  5.0  6.0  NaN
2  7.0  NaN  8.0    F
3  NaN  NaN  NaN    F

In [ ]:
# Let us add one more column in dataframe
data = [
    [1,2,3,'M',1],
    [np.nan,5,6,np.nan,2],
    [7,np.nan,8,'F',3],
    [np.nan,np.nan,np.nan,'F',4]
]

In [ ]:
dframe = pd.DataFrame(data,columns=['a','b','c','d','e'])
dframe

     a    b    c    d  e
0  1.0  2.0  3.0    M  1
1  NaN  5.0  6.0  NaN  2
2  7.0  NaN  8.0    F  3
3  NaN  NaN  NaN    F  4

In [ ]:
newdf = dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c,})
newdf

     a    b    c    d  e
0  1.0  2.0  3.0    M  1
1  4.0  5.0  6.0  NaN  2
2  7.0  3.5  8.0    F  3
3  4.0  3.5  5.7    F  4

In [ ]:
# drop row which have null values
dframe.dropna() # by default axis=0 i.e. refer rows

     a    b    c  d  e
0  1.0  2.0  3.0  M  1

In [ ]:
dframe

     a    b    c    d  e
0  1.0  2.0  3.0    M  1
1  NaN  5.0  6.0  NaN  2
2  7.0  NaN  8.0    F  3
3  NaN  NaN  NaN    F  4

In [ ]:
# drop columns which have null values
dframe.dropna(axis=1) # axis=0 is rows, axis=1 is columns, by default axis=0

   e
0  1
1  2
2  3
3  4

**Handling Duplicates**

In [ ]:
ddup = pd.DataFrame({'col1':['A','A','B','B','B'],'col2':[2,2,2,3,3]})
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [ ]:
ddup.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
ddup.duplicated().sum()

np.int64(2)

In [ ]:
ddup.drop_duplicates()

  col1  col2
0    A     2
2    B     2
3    B     3

In [ ]:
ddup # original dataframe is not changed

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [ ]:
# to make changes in original dataframe use inplace=True
ddup.drop_duplicates(ignore_index=True,inplace=True) #ignore_index=True will reset the index in sequential manner

In [ ]:
ddup

  col1  col2
0    A     2
1    B     2
2    B     3

**Rename Columns**

In [ ]:
ddup

  col1  col2
0    A     2
1    B     2
2    B     3

In [ ]:
ddup.rename(columns={'col1':'Alpha','col2':'Num'},inplace=True)

In [ ]:
ddup

  Alpha  Num
0     A    2
1     B    2
2     B    3

**Connecting Dataframes**

In [ ]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])
df1

   a  b  c
0  1  2  3
1  4  5  6

In [ ]:
df2 = pd.DataFrame([[10,20,30],[40,50,60]],columns=['a','b','c'])
df2

    a   b   c
0  10  20  30
1  40  50  60

In [ ]:
df3 = pd.DataFrame([[11,22],[33,44]],columns=['c1','c2'])
df3

   c1  c2
0  11  22
1  33  44

In [ ]:
d1 = {'movieid':[1,2,3,4,5],
      'title':['Leo','Jawan','Gadar','Pathan','Uri']}
movies = pd.DataFrame(d1)

In [ ]:
import numpy as np
d2 = {'memid':[1,2,3,4],
      'name':['Tom','Tim','Jon','Jim'],
      'movieid':[1,np.nan,3,5]}
members = pd.DataFrame(d2)

**concat()**

In [ ]:
df1

   a  b  c
0  1  2  3
1  4  5  6

In [ ]:
df2

    a   b   c
0  10  20  30
1  40  50  60

In [ ]:
pd.concat([df1,df2],ignore_index=True) #ignore_index=True will reset the index in sequential manner

    a   b   c
0   1   2   3
1   4   5   6
2  10  20  30
3  40  50  60

**join()**

In [ ]:
df3

   c1  c2
0  11  22
1  33  44

In [ ]:
df1.join(df3)

   a  b  c  c1  c2
0  1  2  3  11  22
1  4  5  6  33  44

**merge()**

In [ ]:
movies

   movieid   title
0        1     Leo
1        2   Jawan
2        3   Gadar
3        4  Pathan
4        5     Uri

In [ ]:
members

   memid name  movieid
0      1  Tom      1.0
1      2  Tim      NaN
2      3  Jon      3.0
3      4  Jim      5.0

In [ ]:
# inner join
pd.merge(movies,members, on='movieid',how='inner') # if how= not specified then also inner join will be done by default

   movieid  title  memid name
0        1    Leo      1  Tom
1        3  Gadar      3  Jon
2        5    Uri      4  Jim

In [ ]:

pd.merge(movies,members, on='movieid',how='left')

   movieid   title  memid name
0        1     Leo    1.0  Tom
1        2   Jawan    NaN  NaN
2        3   Gadar    3.0  Jon
3        4  Pathan    NaN  NaN
4        5     Uri    4.0  Jim

In [ ]:

pd.merge(movies,members, on='movieid',how='right')

   movieid  title  memid name
0      1.0    Leo      1  Tom
1      NaN    NaN      2  Tim
2      3.0  Gadar      3  Jon
3      5.0    Uri      4  Jim

In [ ]:
pd.merge(movies,members, on='movieid',how='outer') # all movies and all members

   movieid   title  memid name
0      1.0     Leo    1.0  Tom
1      2.0   Jawan    NaN  NaN
2      3.0   Gadar    3.0  Jon
3      4.0  Pathan    NaN  NaN
4      5.0     Uri    4.0  Jim
5      NaN     NaN    2.0  Tim

**Sorting**

In [ ]:
import pandas as pd
sal = pd.read_csv('/content/Salaries.csv')

In [ ]:
sal.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [ ]:
sal.sort_values('salary') # sal.sort_values(by='salary')

         rank discipline  phd  service     sex  salary
9        Prof          A   51       51    Male   57800
54  AssocProf          A   25       22  Female   62884
66   AsstProf          A    7        6  Female   63100
71  AssocProf          B   12        9  Female   71065
55   AsstProf          A    2        0  Female   72500
..        ...        ...  ...      ...     ...     ...
31       Prof          B   22       21    Male  155750
27       Prof          A   45       43    Male  155865
72       Prof          B   24       15  Female  161101
13       Prof          B   35       33    Male  162200
0        Prof          B   56       49    Male  186960

[78 rows x 6 columns]

In [ ]:
sal.sort_values('salary',ascending=False)

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
13       Prof          B   35       33    Male  162200
72       Prof          B   24       15  Female  161101
27       Prof          A   45       43    Male  155865
31       Prof          B   22       21    Male  155750
..        ...        ...  ...      ...     ...     ...
55   AsstProf          A    2        0  Female   72500
71  AssocProf          B   12        9  Female   71065
66   AsstProf          A    7        6  Female   63100
54  AssocProf          A   25       22  Female   62884
9        Prof          A   51       51    Male   57800

[78 rows x 6 columns]

In [ ]:
# sort based on service in descending order
sal.sort_values('service',ascending=False)

        rank discipline  phd  service     sex  salary
9       Prof          A   51       51    Male   57800
0       Prof          B   56       49    Male  186960
36      Prof          B   45       45    Male  146856
27      Prof          A   45       43    Male  155865
40      Prof          A   39       36  Female  137000
..       ...        ...  ...      ...     ...     ...
17  AsstProf          B    4        0    Male   92000
43  AsstProf          B    5        0  Female   77000
23  AsstProf          A    2        0    Male   85000
55  AsstProf          A    2        0  Female   72500
52      Prof          A   12        0  Female  105000

[78 rows x 6 columns]

**Lambda Function**
A lambda function in Python is a small anonymous function — meaning it doesn’t have a name (unless you assign it one) and is typically used for short, simple operations.
Syntax: **lambda arguments: expression**

*   Suppose we want to write a function which will look at the years of experience.
*   If it is more than 20 years we will say "Very Experienced" and if less than 20, we will say "Less Experienced". For that let us write lambda function.

In [ ]:
fn = lambda x : 'Very Experienced' if x > 20 else 'Less Experienced'

In [ ]:
fn(30)

'Very Experienced'

In [ ]:
fn(10)

'Less Experienced'

In [ ]:
sal

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

Suppose we want to apply this function on each record of our dataframe i.e. on Service column. For that use apply() function. It is a row level function.

In [ ]:
sal['service'].apply(lambda x : 'Very Experienced' if x > 20 else 'Less Experienced')

0     Very Experienced
1     Less Experienced
2     Less Experienced
3     Very Experienced
4     Less Experienced
            ...
73    Less Experienced
74    Less Experienced
75    Less Experienced
76    Less Experienced
77    Less Experienced
Name: service, Length: 78, dtype: object

In [ ]:
sal

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

To add this column in your existing dataframe

In [ ]:
sal['status'] = sal['service'].apply(lambda x : 'Very Experienced' if x > 20 else 'Less Experienced')

In [ ]:
sal.head(15)

         rank discipline  phd  service   sex  salary            status
0        Prof          B   56       49  Male  186960  Very Experienced
1        Prof          A   12        6  Male   93000  Less Experienced
2        Prof          A   23       20  Male  110515  Less Experienced
3        Prof          A   40       31  Male  131205  Very Experienced
4        Prof          B   20       18  Male  104800  Less Experienced
5        Prof          A   20       20  Male  122400  Less Experienced
6   AssocProf          A   20       17  Male   81285  Less Experienced
7        Prof          A   18       18  Male  126300  Less Experienced
8        Prof          A   29       19  Male   94350  Less Experienced
9        Prof          A   51       51  Male   57800  Very Experienced
10       Prof          B   39       33  Male  128250  Very Experienced
11       Prof          B   23       23  Male  134778  Very Experienced
12   AsstProf          B    1        0  Male   88000  Less Experienced
13       Prof          B   35       33  Male  162200  Very Experienced
14       Prof          B   25       19  Male  153750  Less Experienced

**Math Functios**

In [ ]:
import math

In [ ]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [ ]:
math.pow(10,5)

100000.0

In [ ]:
math.trunc(4.1276) # removes all fractions

4

In [ ]:
round(4.2777,2) # this function is not there in math library. It is directly available in python

4.28

In [ ]:
round(4.22,1)

4.2

In [ ]:
round(4.56667,3)

4.567

In [ ]:
math.sqrt(9)

3.0

In [ ]:
math.pi # constant

3.141592653589793

**Calendar**

In [ ]:
import calendar

In [ ]:
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_get_default_locale',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [ ]:
print("Calendar of the year 2025 is : ")
print (calendar.calendar(2025,1,1,5,3)) # w,l,c,m, 10: distance between 2 months
# Return a m-column calendar for an entire year as a multi-line string.
# Optional parameters w, l, and c are for date column width, lines per week, and number of spaces between month columns, respectively.
# Try changing w l c m values
# The w parameter sets the date column width, l is the number of lines per week,
# c sets the spacing between month columns, and m is the number of month columns.

Calendar of the year 2025 is :
                                 2025

      January                  February                  March
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
       1  2  3  4  5                     1  2                     1  2
 6  7  8  9 10 11 12      3  4  5  6  7  8  9      3  4  5  6  7  8  9
13 14 15 16 17 18 19     10 11 12 13 14 15 16     10 11 12 13 14 15 16
20 21 22 23 24 25 26     17 18 19 20 21 22 23     17 18 19 20 21 22 23
27 28 29 30 31           24 25 26 27 28           24 25 26 27 28 29 30
                                                  31

       April                     May                      June
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6               1  2  3  4                        1
 7  8  9 10 11 12 13      5  6  7  8  9 10 11      2  3  4  5  6  7  8
14 15 16 17 18 19 20     12 13 14 15 16 17 18      9 10 11 12 13 14 15
21 22 23 24 25 26 27     19 20 21 22 23 24 25     16 17 18 19 20 21 22
28 29 30                 26 27 28 29 30 31        23 24 25 26 27 28 29
                                                  30

        July                    August                 September
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                  1  2  3      1  2  3  4  5  6  7
 7  8  9 10 11 12 13      4  5  6  7  8  9 10      8  9 10 11 12 13 14
14 15 16 17 18 19 20     11 12 13 14 15 16 17     15 16 17 18 19 20 21
21 22 23 24 25 26 27     18 19 20 21 22 23 24     22 23 24 25 26 27 28
28 29 30 31              25 26 27 28 29 30 31     29 30

      October                  November                 December
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
       1  2  3  4  5                     1  2      1  2  3  4  5  6  7
 6  7  8  9 10 11 12      3  4  5  6  7  8  9      8  9 10 11 12 13 14
13 14 15 16 17 18 19     10 11 12 13 14 15 16     15 16 17 18 19 20 21
20 21 22 23 24 25 26     17 18 19 20 21 22 23     22 23 24 25 26 27 28
27 28 29 30 31           24 25 26 27 28 29 30     29 30 31

In [ ]:
print ("The Jan month of 2025 is : ") # print calendar of specific month
print(calendar.month(2025,1,2,1)) # Year,Month,2,1 are the spacings

The Jan month of 2025 is :
    January 2025
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31

In [ ]:
calendar.monthcalendar(2025,1) # day wise for dec 2028, Mon to Sunday

[[0, 0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26],
 [27, 28, 29, 30, 31, 0, 0]]

In [ ]:
calendar.isleap(2024)

True

**datetime module**

In [ ]:
from datetime import date # date related functions

In [ ]:
today = date.today()
print("Today's date is: ",today)

Today's date is:  2025-02-24

In [ ]:
# Current date in different formats
# dd/mm/YY
d1 = today.strftime("%d/%m/%Y") # dd/mm/yyyy 27/08/2024
print("d1 =", d1)

# Textual month, day and year
d2 = today.strftime("%B %d, %Y") # August 27, 2024, %B-Full month name, %Y-yyyy, %y-yy
print("d2 =", d2)

# mm/dd/yy
d3 = today.strftime("%m/%d/%y") # mm/dd/yy 08/27/24
print("d3 =", d3)

# Month abbreviation, day and year
d4 = today.strftime("%b-%d-%Y") # Dec-15-2023, %b-abb. of monthname
print("d4 =", d4)

d1 = 27/08/2024
d2 = August 27, 2024
d3 = 08/27/24
d4 = Aug-27-2024

In [ ]:
from datetime import datetime # date and time related functions
now = datetime.now()

print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("date and time =", dt_string)

now = 2024-12-04 06:51:40.594424
date and time = 04/12/2024 06:51:40

In [ ]:
import datetime

In [ ]:
x = datetime.datetime.now()
print(x)

2024-07-23 03:51:22.074340

In [ ]:
print(x.year)

2024

In [ ]:
print(x.month)

7

In [ ]:
print(x.strftime("%b")) #strftime: string formatted time
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

Jul

In [ ]:
print(x.strftime("%B"))

July

In [ ]:
print(x.strftime("%d-%b-%Y"))

05-Jul-2024

In [ ]:
print(x.strftime("%d-%m-%y"))

03-07-24

**Date**
You can find difference between 2 dates

In [ ]:
from datetime import date

In [ ]:
print("Today's date: ",date.today())

Today's date:  2024-12-04

In [ ]:
date1 = date(2020,2,25)
date2 = date(2023,12,14)

In [ ]:
type(date1)

datetime.date

In [ ]:
diff = date2 - date1

In [ ]:
type(diff) # after subtraction we get a new data type as timedelta

datetime.timedelta

In [ ]:
diff

datetime.timedelta(days=1388)

In [ ]:
diff.days

1388

In [ ]:
(date2 - date1).days

1388